---

- hosts: localhost
  sudo: yes
  handlers:

  tasks:
   - name: drop_caches
     raw: echo 3 > /proc/sys/vm/drop_caches
     when: ( ansible_memory_mb.swap.used > 0 and ansible_memory_mb.real.free < ansible_memory_mb.swap.used )
   - name: swapoff -a && swapon -a
     raw: swapoff -a && swapon -a
     when: ( ansible_memory_mb.swap.used > 0 and ansible_memory_mb.real.free > ansible_memory_mb.swap.used )
   - name: swap more than RAM
     debug: msg="swap more than RAM"
     failed_when: (ansible_memory_mb.real.free < ansible_memory_mb.swap.used )
